
package rsa_examen;

/**
 *
 * @author Daniel Rodriguez Flores 5IV8
 */

//importamos las librerias
import java.math.BigInteger;
import java.io.*;
import java.util.Observable;
import java.util.Observer;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

public class Interfaz_Cliente1 extends javax.swing.JFrame implements Observer{

    
    private RSA cifradoRSA;
    /**
     * Creates new form Interfaz_Cliente1
     */
    public Interfaz_Cliente1() {
        initComponents();
        
//        Servidor servidor = new Servidor(9876);
//        servidor.addObserver(this);
//        Thread t = new Thread(servidor);
//        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cifrar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numero_p = new javax.swing.JTextField();
        numero_q = new javax.swing.JTextField();
        btn_numeros_primos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        calcular_numeros = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensaje_cifrado_des = new javax.swing.JTextArea();
        clave_d = new javax.swing.JLabel();
        clave_e = new javax.swing.JLabel();
        phi = new javax.swing.JLabel();
        modulo_n = new javax.swing.JLabel();
        btn_enviar_datos = new javax.swing.JButton();
        btn_descifrar = new javax.swing.JButton();
        btn_cifrar = new javax.swing.JButton();

        btn_cifrar1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_cifrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa_examen/img/sister 1.png"))); // NOI18N
        btn_cifrar1.setText("Cifrar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cifrado RSA");
        setMaximumSize(new java.awt.Dimension(620, 752));
        setMinimumSize(new java.awt.Dimension(620, 752));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 238, 223));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cifrado RSA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel2.setText("Número p:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel3.setText("Número q:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        numero_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_pActionPerformed(evt);
            }
        });
        jPanel1.add(numero_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 220, 30));
        jPanel1.add(numero_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 220, 30));

        btn_numeros_primos.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_numeros_primos.setText("Generar Números Primos");
        btn_numeros_primos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numeros_primosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_numeros_primos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 220, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 15));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 580, 20));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel4.setText("Mensaje Final:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel5.setText("Módulo n:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel6.setText("Phi:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel7.setText("Clave e:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        calcular_numeros.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        calcular_numeros.setText("Calcular Números");
        calcular_numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_numerosActionPerformed(evt);
            }
        });
        jPanel1.add(calcular_numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 170, 40));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 15));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 580, 20));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel8.setText("Clave d:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        mensaje.setColumns(20);
        mensaje.setRows(5);
        jScrollPane1.setViewportView(mensaje);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 390, 130));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel9.setText("Mensaje:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        mensaje_cifrado_des.setColumns(20);
        mensaje_cifrado_des.setRows(5);
        jScrollPane2.setViewportView(mensaje_cifrado_des);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 560, 130));

        clave_d.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        clave_d.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(clave_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 230, 20));

        clave_e.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        clave_e.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(clave_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 230, 20));

        phi.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        phi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(phi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 230, 20));

        modulo_n.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        modulo_n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(modulo_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 230, 20));

        btn_enviar_datos.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_enviar_datos.setText("Enviar Datos");
        btn_enviar_datos.setEnabled(false);
        btn_enviar_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_datosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enviar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 160, 40));

        btn_descifrar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_descifrar.setText("Descifrar");
        btn_descifrar.setEnabled(false);
        btn_descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_descifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 140, 40));

        btn_cifrar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn_cifrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa_examen/img/sister 1.png"))); // NOI18N
        btn_cifrar.setText("Cifrar");
        btn_cifrar.setEnabled(false);
        btn_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 160, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//--------------------------------Evento para generar los numeros primos
    private void btn_numeros_primosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numeros_primosActionPerformed
        
        rsa=new RSA(10);
        
        //Obtenemos los numeros del textfield
        numero_p.setText(""+rsa.dameP());
        numero_q.setText(""+rsa.dameQ());
        
    }//GEN-LAST:event_btn_numeros_primosActionPerformed
    private RSA rsa;
    
    
    private void numero_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_pActionPerformed

    
//--------------------Evento para el boton de calcular n, phi, e, d-------------------------
    private void calcular_numerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_numerosActionPerformed
        
        //Verificamos que los campos esten llenos
        if(!numero_p.getText().isEmpty()||!numero_q.getText().isEmpty()){
            if(!numero_p.getText().isEmpty()){
                if(!numero_q.getText().isEmpty()){
                    //Obtenemos los valores de p y q
                    BigInteger p=new BigInteger(numero_p.getText());
                    BigInteger q=new  BigInteger(numero_q.getText());
                    
                    //Claculamos los valores de d y e
                    cifradoRSA=new RSA(p, q,10);
                    clave_d.setText(""+cifradoRSA.dameD());
                    clave_e.setText(""+cifradoRSA.dameE());
                    modulo_n.setText(""+cifradoRSA.dameN());
                    phi.setText(""+cifradoRSA.damePhi());
                    
                    //Habilitamos el boton para cifrar
                    btn_cifrar.setEnabled(true);
                    btn_descifrar.setEnabled(true);
                    btn_enviar_datos.setEnabled(true);
                
                }else{
                    JOptionPane.showMessageDialog(this, "Ingrese el valor de q");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ingrese el valor de p");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese el valor de p y q");
        }
    }//GEN-LAST:event_calcular_numerosActionPerformed

    private void btn_enviar_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_datosActionPerformed
        
        String mensaje_c = this.mensaje_cifrado_des.getText();
        //this.mensaje_cifrado.append(mensaje_c);
        
        
        //Ip de la otra computadorac
        Cliente c = new Cliente("201.133.229.11",9876,mensaje_c);
        Thread t = new Thread(c);
        t.start();
    }//GEN-LAST:event_btn_enviar_datosActionPerformed

//----------------------------------BOTON PARA DESCIFRAR    
    private void btn_descifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarActionPerformed
         //Descifrar
            String letra="";

            StringTokenizer st=new StringTokenizer(mensaje.getText());
            BigInteger[] textoCifrado = new BigInteger[st.countTokens()];

            for(int i=0;i<textoCifrado.length;i++){
                letra = st.nextToken();
                textoCifrado[i]=new BigInteger(letra);
            }
            mensaje_cifrado_des.setText(cifradoRSA.desencripta(textoCifrado));
    }//GEN-LAST:event_btn_descifrarActionPerformed

    //------------------------------Boton para CIFRAR
    private void btn_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarActionPerformed
        //Creamos la variable para encriptar el texto que se ingrese en el textarea
        BigInteger[] txtCifrado = cifradoRSA.encriptar(mensaje.getText());
        mensaje_cifrado_des.setText("");
        
        //Recorremos todo el mensaje
        for(int i=0; i<txtCifrado.length; i++) {
            
            mensaje_cifrado_des.setText(mensaje_cifrado_des.getText()+txtCifrado[i].toString()+"\t");
            
            //Ciframos el texto
            if(i != txtCifrado.length-1){
                mensaje_cifrado_des.setText(mensaje_cifrado_des.getText()+"");
                
            }
        }
    }//GEN-LAST:event_btn_cifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Cliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Cliente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cifrar;
    private javax.swing.JButton btn_cifrar1;
    private javax.swing.JButton btn_descifrar;
    private javax.swing.JButton btn_enviar_datos;
    private javax.swing.JButton btn_numeros_primos;
    private javax.swing.JButton calcular_numeros;
    private javax.swing.JLabel clave_d;
    private javax.swing.JLabel clave_e;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JTextArea mensaje_cifrado_des;
    private javax.swing.JLabel modulo_n;
    private javax.swing.JTextField numero_p;
    private javax.swing.JTextField numero_q;
    private javax.swing.JLabel phi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        //this.mensaje_cifrado.append((String) arg);
    }
    

}
