/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsa_examen;

import java.math.BigInteger;
import java.util.Observable;
import java.util.Observer;
import java.util.StringTokenizer;

/**
 *
 * @author Daniel
 */
public class Interfaz_Descifrar extends javax.swing.JFrame implements Observer{

    private RSA cifradoRSA;
    public Interfaz_Descifrar() {
        initComponents();
        Servidor servidor = new Servidor(9876);
        servidor.addObserver(this);
        Thread t = new Thread(servidor);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje_cifrado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensaje_descifrado = new javax.swing.JTextArea();
        clave_d = new javax.swing.JTextField();
        modulo_n = new javax.swing.JTextField();
        numero_p = new javax.swing.JTextField();
        numero_q = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phi = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_descifrar1 = new javax.swing.JToggleButton();

        jLabel8.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel8.setText("Número p:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Descifrar RSA");

        jPanel1.setBackground(new java.awt.Color(204, 212, 225));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensaje_cifrado.setColumns(20);
        mensaje_cifrado.setRows(5);
        jScrollPane1.setViewportView(mensaje_cifrado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 440, 100));

        mensaje_descifrado.setColumns(20);
        mensaje_descifrado.setRows(5);
        jScrollPane2.setViewportView(mensaje_descifrado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 520, 140));

        clave_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clave_dActionPerformed(evt);
            }
        });
        jPanel1.add(clave_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 250, 30));

        modulo_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulo_nActionPerformed(evt);
            }
        });
        jPanel1.add(modulo_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 250, 30));

        numero_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_pActionPerformed(evt);
            }
        });
        jPanel1.add(numero_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 250, 30));
        jPanel1.add(numero_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 250, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Descifrado RSA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel9.setText("Número p:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel10.setText("Número q:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel5.setText("Módulo n:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel6.setText("Phi:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, -1));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 16)); // NOI18N
        jLabel11.setText("Clave d:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        phi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phiActionPerformed(evt);
            }
        });
        jPanel1.add(phi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, 30));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 15));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 580, 20));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel4.setText("Mensaje cifrado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel12.setText("Mensaje descifrado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        btn_descifrar1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btn_descifrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa_examen/img/sister 2.png"))); // NOI18N
        btn_descifrar1.setText("Descifrar");
        btn_descifrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_descifrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clave_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clave_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clave_dActionPerformed

    private void modulo_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulo_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modulo_nActionPerformed

    private void numero_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_pActionPerformed

    private void phiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phiActionPerformed

    private void btn_descifrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrar1ActionPerformed
         //Descifrar
        String letra="";

        BigInteger p=new BigInteger(numero_p.getText());
        BigInteger q=new  BigInteger(numero_q.getText());
        cifradoRSA=new RSA(p, q,10);
        cifradoRSA.dameD().equals(clave_d);
        cifradoRSA.damePhi().equals(phi);
        cifradoRSA.dameN().equals(modulo_n);
        StringTokenizer st=new StringTokenizer(mensaje_cifrado.getText());
        BigInteger[] textoCifrado = new BigInteger[st.countTokens()];

        for(int i=0;i<textoCifrado.length;i++){
            letra = st.nextToken();
            textoCifrado[i]=new BigInteger(letra);
        }
        mensaje_descifrado.setText(cifradoRSA.desencripta(textoCifrado));
    }//GEN-LAST:event_btn_descifrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Descifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Descifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Descifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Descifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Descifrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_descifrar1;
    private javax.swing.JTextField clave_d;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea mensaje_cifrado;
    private javax.swing.JTextArea mensaje_descifrado;
    private javax.swing.JTextField modulo_n;
    private javax.swing.JTextField numero_p;
    private javax.swing.JTextField numero_q;
    private javax.swing.JTextField phi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.mensaje_cifrado.append((String) arg);
    }
}
